# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: latch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="latch.proto",
    package="service",
    syntax="proto3",
    serialized_options=b"Z)github.com/latchai/latch/go/pkg/servicepb",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0blatch.proto\x12\x07service\x1a\x1fgoogle/protobuf/timestamp.proto"\r\n\x0bPingRequest"\x1c\n\tPingReply\x12\x0f\n\x07success\x18\x01 \x01(\x08"-\n\x10LaunchJobRequest\x12\x19\n\x03job\x18\x01 \x01(\x0b\x32\x0c.service.Job"!\n\x0eLaunchJobReply\x12\x0f\n\x07success\x18\x01 \x01(\x08"\x9d\x01\n\x03Job\x12\x0e\n\x06script\x18\x01 \x01(\t\x12\x38\n\x0epythonPackages\x18\x02 \x03(\x0b\x32 .service.Job.PythonPackagesEntry\x12\x15\n\rpythonVersion\x18\x03 \x01(\t\x1a\x35\n\x13PythonPackagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x7f\n\x06\x44\x61\x65mon\x12\x32\n\x04Ping\x12\x14.service.PingRequest\x1a\x12.service.PingReply"\x00\x12\x41\n\tLaunchJob\x12\x19.service.LaunchJobRequest\x1a\x17.service.LaunchJobReply"\x00\x42+Z)github.com/latchai/latch/go/pkg/servicepbb\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,
    ],
)


_PINGREQUEST = _descriptor.Descriptor(
    name="PingRequest",
    full_name="service.PingRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=57,
    serialized_end=70,
)


_PINGREPLY = _descriptor.Descriptor(
    name="PingReply",
    full_name="service.PingReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="success",
            full_name="service.PingReply.success",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=72,
    serialized_end=100,
)


_LAUNCHJOBREQUEST = _descriptor.Descriptor(
    name="LaunchJobRequest",
    full_name="service.LaunchJobRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="job",
            full_name="service.LaunchJobRequest.job",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=102,
    serialized_end=147,
)


_LAUNCHJOBREPLY = _descriptor.Descriptor(
    name="LaunchJobReply",
    full_name="service.LaunchJobReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="success",
            full_name="service.LaunchJobReply.success",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=149,
    serialized_end=182,
)


_JOB_PYTHONPACKAGESENTRY = _descriptor.Descriptor(
    name="PythonPackagesEntry",
    full_name="service.Job.PythonPackagesEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="service.Job.PythonPackagesEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="service.Job.PythonPackagesEntry.value",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"8\001",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=289,
    serialized_end=342,
)

_JOB = _descriptor.Descriptor(
    name="Job",
    full_name="service.Job",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="script",
            full_name="service.Job.script",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="pythonPackages",
            full_name="service.Job.pythonPackages",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="pythonVersion",
            full_name="service.Job.pythonVersion",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _JOB_PYTHONPACKAGESENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=185,
    serialized_end=342,
)

_LAUNCHJOBREQUEST.fields_by_name["job"].message_type = _JOB
_JOB_PYTHONPACKAGESENTRY.containing_type = _JOB
_JOB.fields_by_name["pythonPackages"].message_type = _JOB_PYTHONPACKAGESENTRY
DESCRIPTOR.message_types_by_name["PingRequest"] = _PINGREQUEST
DESCRIPTOR.message_types_by_name["PingReply"] = _PINGREPLY
DESCRIPTOR.message_types_by_name["LaunchJobRequest"] = _LAUNCHJOBREQUEST
DESCRIPTOR.message_types_by_name["LaunchJobReply"] = _LAUNCHJOBREPLY
DESCRIPTOR.message_types_by_name["Job"] = _JOB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType(
    "PingRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _PINGREQUEST,
        "__module__": "latch_pb2"
        # @@protoc_insertion_point(class_scope:service.PingRequest)
    },
)
_sym_db.RegisterMessage(PingRequest)

PingReply = _reflection.GeneratedProtocolMessageType(
    "PingReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _PINGREPLY,
        "__module__": "latch_pb2"
        # @@protoc_insertion_point(class_scope:service.PingReply)
    },
)
_sym_db.RegisterMessage(PingReply)

LaunchJobRequest = _reflection.GeneratedProtocolMessageType(
    "LaunchJobRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _LAUNCHJOBREQUEST,
        "__module__": "latch_pb2"
        # @@protoc_insertion_point(class_scope:service.LaunchJobRequest)
    },
)
_sym_db.RegisterMessage(LaunchJobRequest)

LaunchJobReply = _reflection.GeneratedProtocolMessageType(
    "LaunchJobReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _LAUNCHJOBREPLY,
        "__module__": "latch_pb2"
        # @@protoc_insertion_point(class_scope:service.LaunchJobReply)
    },
)
_sym_db.RegisterMessage(LaunchJobReply)

Job = _reflection.GeneratedProtocolMessageType(
    "Job",
    (_message.Message,),
    {
        "PythonPackagesEntry": _reflection.GeneratedProtocolMessageType(
            "PythonPackagesEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _JOB_PYTHONPACKAGESENTRY,
                "__module__": "latch_pb2"
                # @@protoc_insertion_point(class_scope:service.Job.PythonPackagesEntry)
            },
        ),
        "DESCRIPTOR": _JOB,
        "__module__": "latch_pb2"
        # @@protoc_insertion_point(class_scope:service.Job)
    },
)
_sym_db.RegisterMessage(Job)
_sym_db.RegisterMessage(Job.PythonPackagesEntry)


DESCRIPTOR._options = None
_JOB_PYTHONPACKAGESENTRY._options = None

_DAEMON = _descriptor.ServiceDescriptor(
    name="Daemon",
    full_name="service.Daemon",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=344,
    serialized_end=471,
    methods=[
        _descriptor.MethodDescriptor(
            name="Ping",
            full_name="service.Daemon.Ping",
            index=0,
            containing_service=None,
            input_type=_PINGREQUEST,
            output_type=_PINGREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="LaunchJob",
            full_name="service.Daemon.LaunchJob",
            index=1,
            containing_service=None,
            input_type=_LAUNCHJOBREQUEST,
            output_type=_LAUNCHJOBREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_DAEMON)

DESCRIPTOR.services_by_name["Daemon"] = _DAEMON

# @@protoc_insertion_point(module_scope)
