# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import latch_pb2 as latch__pb2


class DaemonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
            "/service.Daemon/Ping",
            request_serializer=latch__pb2.PingRequest.SerializeToString,
            response_deserializer=latch__pb2.PingReply.FromString,
        )
        self.LaunchJob = channel.unary_unary(
            "/service.Daemon/LaunchJob",
            request_serializer=latch__pb2.LaunchJobRequest.SerializeToString,
            response_deserializer=latch__pb2.LaunchJobReply.FromString,
        )


class DaemonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LaunchJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Ping": grpc.unary_unary_rpc_method_handler(
            servicer.Ping,
            request_deserializer=latch__pb2.PingRequest.FromString,
            response_serializer=latch__pb2.PingReply.SerializeToString,
        ),
        "LaunchJob": grpc.unary_unary_rpc_method_handler(
            servicer.LaunchJob,
            request_deserializer=latch__pb2.LaunchJobRequest.FromString,
            response_serializer=latch__pb2.LaunchJobReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "service.Daemon", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Daemon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/service.Daemon/Ping",
            latch__pb2.PingRequest.SerializeToString,
            latch__pb2.PingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def LaunchJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/service.Daemon/LaunchJob",
            latch__pb2.LaunchJobRequest.SerializeToString,
            latch__pb2.LaunchJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
