"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    ScalarMap as google___protobuf___internal___containers___ScalarMap,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Mapping as typing___Mapping,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class PingRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___PingRequest = PingRequest

class PingReply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    success: builtin___bool = ...

    def __init__(self,
        *,
        success : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"success",b"success"]) -> None: ...
type___PingReply = PingReply

class LaunchJobRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def job(self) -> type___Job: ...

    def __init__(self,
        *,
        job : typing___Optional[type___Job] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"job",b"job"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"job",b"job"]) -> None: ...
type___LaunchJobRequest = LaunchJobRequest

class LaunchJobReply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    success: builtin___bool = ...

    def __init__(self,
        *,
        success : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"success",b"success"]) -> None: ...
type___LaunchJobReply = LaunchJobReply

class Job(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class PythonPackagesEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: typing___Text = ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
    type___PythonPackagesEntry = PythonPackagesEntry

    script: typing___Text = ...
    pythonVersion: typing___Text = ...

    @property
    def pythonPackages(self) -> google___protobuf___internal___containers___ScalarMap[typing___Text, typing___Text]: ...

    def __init__(self,
        *,
        script : typing___Optional[typing___Text] = None,
        pythonPackages : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        pythonVersion : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"pythonPackages",b"pythonPackages",u"pythonVersion",b"pythonVersion",u"script",b"script"]) -> None: ...
type___Job = Job
